# Generated by Django 4.2.4 on 2023-09-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='discounts',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
    ]
