# Generated by Django 4.2.4 on 2023-09-18 17:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_title_az_product_title_en_product_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_az',
            field=ckeditor.fields.RichTextField(help_text='CONTENT COLUMN ', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=ckeditor.fields.RichTextField(help_text='CONTENT COLUMN ', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_ru',
            field=ckeditor.fields.RichTextField(help_text='CONTENT COLUMN ', null=True),
        ),
    ]
