# Generated by Django 4.2.4 on 2023-10-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
