# Generated by Django 4.2.4 on 2023-10-31 15:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='CONTENT COLUMN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_az',
            field=ckeditor.fields.RichTextField(help_text='CONTENT COLUMN', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_en',
            field=ckeditor.fields.RichTextField(help_text='CONTENT COLUMN', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_ru',
            field=ckeditor.fields.RichTextField(help_text='CONTENT COLUMN', null=True),
        ),
    ]
