# Generated by Django 4.2.4 on 2023-10-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_carouselitem_buuton_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('buuton_text', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('content', models.TextField()),
                ('video', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Discounts',
        ),
        migrations.DeleteModel(
            name='Homecategoriesimage',
        ),
        migrations.DeleteModel(
            name='Homecategoriesimage2',
        ),
    ]
